// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopTLA.Models.Domain;

#nullable disable

namespace ShopTLA.Migrations
{
    [DbContext(typeof(ShopTlaContext))]
    partial class ShopTlaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopTLA.Models.Category", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatId"));

                    b.Property<string>("CatDescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CatLastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CatName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CatId")
                        .HasName("PK__Categori__6A1C8AFA1C46400F");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ShopTLA.Models.Customer", b =>
                {
                    b.Property<int>("CusId")
                        .HasColumnType("int");

                    b.Property<string>("CusAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CusDateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("CusEmail")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CusLastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CusPhone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("CusId")
                        .HasName("PK__Customer__2F187110E88EB5DF");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ShopTLA.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<string>("EmpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EmpDateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("EmpEmail")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("EmpLastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmpPhone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<double?>("EmpSalary")
                        .HasColumnType("float");

                    b.HasKey("EmpId")
                        .HasName("PK__Employee__AF2DBB992BF77CF3");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ShopTLA.Models.Nation", b =>
                {
                    b.Property<int>("NatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NatId"));

                    b.Property<DateTime?>("NatLastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NatName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NatId")
                        .HasName("PK__Nations__668041083B4A3E5A");

                    b.ToTable("Nations");
                });

            modelBuilder.Entity("ShopTLA.Models.Order", b =>
                {
                    b.Property<int>("OrdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdId"));

                    b.Property<int?>("CusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OrdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("OrdLastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("OrdStatus")
                        .HasColumnType("int");

                    b.Property<double?>("OrdTotal")
                        .HasColumnType("float");

                    b.HasKey("OrdId")
                        .HasName("PK__Orders__67A28336A51F5815");

                    b.HasIndex("CusId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ShopTLA.Models.OrderDetail", b =>
                {
                    b.Property<int>("DetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetId"));

                    b.Property<DateTime?>("DetLastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<double?>("DetPrice")
                        .HasColumnType("float");

                    b.Property<int?>("DetQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("OrdId")
                        .HasColumnType("int");

                    b.Property<int?>("ProId")
                        .HasColumnType("int");

                    b.HasKey("DetId")
                        .HasName("PK__OrderDet__D8957ADCAEF05231");

                    b.HasIndex("OrdId");

                    b.HasIndex("ProId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("ShopTLA.Models.Product", b =>
                {
                    b.Property<int>("ProId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProId"));

                    b.Property<int?>("CatId")
                        .HasColumnType("int");

                    b.Property<int?>("NatId")
                        .HasColumnType("int");

                    b.Property<string>("ProDescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ProLastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ProName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("ProPrice")
                        .HasColumnType("float");

                    b.HasKey("ProId")
                        .HasName("PK__Products__6202959091DE12B0");

                    b.HasIndex("CatId");

                    b.HasIndex("NatId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ShopTLA.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("TypeUser")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__UserAcco__3214EC07D547027E");

                    b.HasIndex("TypeUser");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("ShopTLA.Models.UserType", b =>
                {
                    b.Property<int>("TypeUser")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TypeUser")
                        .HasName("PK__UserType__E1F318E8051A5C84");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("ShopTLA.Models.Customer", b =>
                {
                    b.HasOne("ShopTLA.Models.UserAccount", "Cus")
                        .WithOne("Customer")
                        .HasForeignKey("ShopTLA.Models.Customer", "CusId")
                        .IsRequired()
                        .HasConstraintName("FK__Customers__CusId__2B3F6F97");

                    b.Navigation("Cus");
                });

            modelBuilder.Entity("ShopTLA.Models.Employee", b =>
                {
                    b.HasOne("ShopTLA.Models.UserAccount", "Emp")
                        .WithOne("Employee")
                        .HasForeignKey("ShopTLA.Models.Employee", "EmpId")
                        .IsRequired()
                        .HasConstraintName("FK__Employees__EmpId__2F10007B");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("ShopTLA.Models.Order", b =>
                {
                    b.HasOne("ShopTLA.Models.Customer", "Cus")
                        .WithMany("Orders")
                        .HasForeignKey("CusId")
                        .HasConstraintName("FK__Orders__CusId__3D5E1FD2");

                    b.Navigation("Cus");
                });

            modelBuilder.Entity("ShopTLA.Models.OrderDetail", b =>
                {
                    b.HasOne("ShopTLA.Models.Order", "Ord")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrdId")
                        .HasConstraintName("FK__OrderDeta__OrdId__4222D4EF");

                    b.HasOne("ShopTLA.Models.Product", "Pro")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProId")
                        .HasConstraintName("FK__OrderDeta__ProId__4316F928");

                    b.Navigation("Ord");

                    b.Navigation("Pro");
                });

            modelBuilder.Entity("ShopTLA.Models.Product", b =>
                {
                    b.HasOne("ShopTLA.Models.Category", "Cat")
                        .WithMany("Products")
                        .HasForeignKey("CatId")
                        .HasConstraintName("FK__Products__CatId__38996AB5");

                    b.HasOne("ShopTLA.Models.Nation", "Nat")
                        .WithMany("Products")
                        .HasForeignKey("NatId")
                        .HasConstraintName("FK__Products__NatId__398D8EEE");

                    b.Navigation("Cat");

                    b.Navigation("Nat");
                });

            modelBuilder.Entity("ShopTLA.Models.UserAccount", b =>
                {
                    b.HasOne("ShopTLA.Models.UserType", "TypeUserNavigation")
                        .WithMany("UserAccounts")
                        .HasForeignKey("TypeUser")
                        .HasConstraintName("FK__UserAccou__TypeU__267ABA7A");

                    b.Navigation("TypeUserNavigation");
                });

            modelBuilder.Entity("ShopTLA.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShopTLA.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ShopTLA.Models.Nation", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShopTLA.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ShopTLA.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ShopTLA.Models.UserAccount", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ShopTLA.Models.UserType", b =>
                {
                    b.Navigation("UserAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
